# Generated by Django 4.2.6 on 2023-11-02 14:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title of ticket')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='description of ticket')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='image')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='ticket created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='creator of ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('headline', models.CharField(max_length=128, verbose_name='title of review')),
                ('body', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='review created at')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.ticket', verbose_name='ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='author of review')),
            ],
        ),
    ]
